services:
  springboot:
      image: enomoto/prometheus
      networks:
        - mynetwork
      container_name: springboot
      restart: unless-stopped
      ports:
        - 8080:8080


  prometheus:
      image: prom/prometheus:v2.35.0
      networks:
        - mynetwork
      container_name: prometheus
      restart: unless-stopped
      volumes:
        - ./data/prometheus/config:/etc/prometheus/
      command:
        - "--config.file=/etc/prometheus/prometheus.yaml"
      ports:
        - 9090:9090
      depends_on:
        - springboot


  grafana:
    image: grafana/grafana-oss:8.5.2
    networks:
      - mynetwork
    pull_policy: always    
    container_name: grafana
    restart: unless-stopped
    user: root
    ports:
      - 3000:3000 # access grafana url
    depends_on:
      - prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      # Enabled for logging
      - GF_LOG_MODE=console file
      - GF_LOG_FILTERS=alerting.notifier.slack:debug alertmanager:debug ngalert:debug

networks:
  mynetwork: